<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.idempiere.karaf</groupId>
        <artifactId>org.idempiere.karaf.parent</artifactId>
        <version>${revision}</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>org.idempiere.karaf.assembly</artifactId>
    <packaging>karaf-assembly</packaging>

    <dependencies>
        <!-- scope is compile so all features (there is only one) are installed into startup.properties and the feature repo itself is not added in etc/org.apache.karaf.features.cfg file -->
        <dependency>
            <groupId>org.apache.karaf.features</groupId>
            <artifactId>framework</artifactId>
            <version>${karaf.version}</version>
            <type>kar</type>
        </dependency>

        <!-- scope is runtime so the feature repo is listed in etc/org.apache.karaf.features.cfg file, and features will installed into the system directory if specify in the plugin configuration -->
        <dependency>
            <groupId>org.apache.karaf.features</groupId>
            <artifactId>standard</artifactId>
            <classifier>features</classifier>
            <version>${karaf.version}</version>
            <type>xml</type>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.features</groupId>
            <artifactId>specs</artifactId>
            <classifier>features</classifier>
            <version>${karaf.version}</version>
            <type>xml</type>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.features</groupId>
            <artifactId>spring</artifactId>
            <version>${karaf.version}</version>
            <type>xml</type>
            <classifier>features</classifier>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.karaf.features</groupId>
            <artifactId>enterprise</artifactId>
            <classifier>features</classifier>
            <version>${karaf.version}</version>
            <type>xml</type>
            <scope>runtime</scope>
        </dependency>

        <!-- external feature repositories-->
        <dependency>
            <groupId>io.hawt</groupId>
            <artifactId>hawtio-karaf</artifactId>
            <version>${hawtio.version}</version>
            <classifier>features</classifier>
            <scope>runtime</scope>
            <type>xml</type>
        </dependency>

        <!-- idempiere feature repository -->
        <dependency>
            <groupId>org.idempiere.karaf</groupId>
            <artifactId>org.idempiere.karaf.feature</artifactId>
            <version>${project.version}</version>
            <classifier>features</classifier>
            <type>xml</type>
            <scope>runtime</scope>
        </dependency>

    </dependencies>

    <build>
        <!-- if you want to include resources in the distribution -->
        <resources>
            <resource>
                <directory>src/main/resources/assembly</directory>
                <filtering>false</filtering>
                <includes>
                    <include>**/*</include>
                </includes>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.karaf.tooling</groupId>
                <artifactId>karaf-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
					<installedFeatures>
                        <feature>wrapper</feature>
                        <feature>aries-blueprint</feature>
                        <feature>shell-compat</feature>
                        <feature>hawtio</feature>
                        <feature>idempiere/${project.version}</feature>
                    </installedFeatures>
                    <startupFeatures>
                        <feature>eventadmin</feature>
                    </startupFeatures>
                    <bootFeatures>
                        <feature>wrap</feature>
                        <feature>classpath</feature>
                        <feature>shell</feature>
                        <feature>feature</feature>
                        <feature>jaas</feature>
                        <feature>ssh</feature>
                        <feature>management</feature>
                        <feature>bundle</feature>
                        <feature>config</feature>
                        <feature>deployer</feature>
                        <feature>diagnostic</feature>
                        <feature>feature</feature>
                        <feature>instance</feature>
                        <feature>kar</feature>
                        <feature>log</feature>
                        <feature>package</feature>
                        <feature>service</feature>
                        <feature>system</feature>
                        <!-- <feature>org.idempiere.karaf.all</feature> -->
                    </bootFeatures>

                    <javase>11</javase>
                    <framework>framework</framework>
                    <archiveZip>true</archiveZip>
                    <archiveTarGz>true</archiveTarGz>
                    <encoding>UTF-8</encoding>
                    <targetFile>idempiere-karaf</targetFile>
                    <!-- <finalName>${project.artifactId}</finalName> -->
                </configuration>

                <executions>
                    <execution>
                        <id>process-resources</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>assembly</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>package</id>
                        <goals>
                            <goal>archive</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>