<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.idempiere</groupId>
		<artifactId>org.idempiere.parent</artifactId>
		<version>${revision}</version>
		<relativePath>../org.idempiere.parent/pom.xml</relativePath>
	</parent>

	<groupId>org.idempiere.karaf</groupId>
	<artifactId>org.idempiere.karaf.parent</artifactId>
	<packaging>pom</packaging>

	<properties>
		<karaf.version>4.4.4</karaf.version>

		<idempiere.plugin.path>plugins</idempiere.plugin.path>
		
		<hawtio.version>2.14.5</hawtio.version>
		<activemq.version>5.17.5</activemq.version>
		<cxf.version>3.5.6</cxf.version>
	</properties>

	<modules>
		<module>feature</module>
		<module>assembly</module>
		<module>repo</module>
	</modules>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.3.0</version>
					<executions>
						<execution>
							<id>filter</id>
							<phase>generate-resources</phase>
							<goals>
								<goal>resources</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.karaf.tooling</groupId>
					<artifactId>karaf-maven-plugin</artifactId>
					<version>${karaf.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.felix</groupId>
					<artifactId>maven-bundle-plugin</artifactId>
					<version>5.1.9</version>
					<extensions>true</extensions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>